dns:
  url: http://localhost:${server.port}

# tencent
#    url: jdbc:mysql://118.25.7.154:3306/ocr?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: yanZq2020.