spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xiaosong?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 2.71828

dns:
  url: http://localhost:${server.port}


# tencent
#    url: jdbc:mysql://118.25.7.154:3306/ocr?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: yanZq2020.