server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
