server:
  port: 10001
  servlet:
    context-path: /${spring.application.name}
# 日志相关
logging:
  config: classpath:logback.xml
spring:
  profiles:
    active: dev

  application:
    name: 5paradigm-ocr

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.100.223.110:3306/ocr?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ocr
    password: ocr8888

  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: uploadFiles/
      max-file-size: 20MB
      max-request-size: 50MB
      resolve-lazily: false

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect

ocr:
#  url: http://47.117.127.63:8868/predict/ocr_system
#  url: http://47.117.127.63:8868/predict/ocr_v50
#  url: http://101.132.24.161:80/predict/ocr_v50
  url: http://101.132.24.161:80/predict/ocr_v50
  appId: wx32e95d3c6fbe4913
  appSecret: e46c212fb7e9fd121dedfab4c0942d21
pdf:
  url: http://47.117.127.63:2234/detect




